"""
Django settings for blog_noticias project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""
import os
from pathlib import Path
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR apunta al directorio raíz del proyecto (un nivel por encima de 'blog_noticias')
BASE_DIR = Path(__file__).resolve().parent.parent 

# Agrega la carpeta 'apps' al path para que Django encuentre las aplicaciones anidadas
sys.path.insert(0, str(BASE_DIR / "apps"))


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wl!#++c=gexp_8c!2_53=ktr7&%^$y$0#kxjb0p*gz2l_%0y*n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
<<<<<<< HEAD
    # Aplicaciones locales:
=======
    # Aplicaciones Personalizadas (Usando la ruta completa para evitar RuntimeError)
>>>>>>> 4f114730af45f235e4354b8ed00145427861897c
    'apps.usuarios.apps.UsuariosConfig',
    'apps.publicaciones.apps.PublicacionesConfig',
    'apps.comentarios.apps.ComentariosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_noticias.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        # 🌟 AJUSTE CRÍTICO 1: DIRS para encontrar templates\base.html
        'DIRS': [
            BASE_DIR / "templates", 
        ],
        
        # APP_DIRS: True encuentra templates en apps\publicaciones\templates\publicaciones\
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [
                # 🌟 AJUSTE CRÍTICO 2: Incluir todos los procesadores para corregir SystemCheckError
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.publicaciones.context_processors.categories_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_noticias.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar' 

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

<<<<<<< HEAD
# 🌟 AGREGAR ESTA LÍNEA 🌟
# Directorios adicionales donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "static", # Apunta a la carpeta 'static' en la raíz del proyecto
]
=======
# CONFIGURACIÓN DE MEDIA (Archivos subidos por el usuario)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
>>>>>>> 4f114730af45f235e4354b8ed00145427861897c


# CONFIGURACIÓN DE AUTENTICACIÓN
# URL a la que se redirige después de un inicio de sesión exitoso
LOGIN_REDIRECT_URL = '/'

<<<<<<< HEAD
# Permite que el enlace directo de Cerrar Sesión funcione sin el formulario POST.
# Esto soluciona el ERROR 405 al anular el requisito de seguridad.
LOGOUT_REDIRECT_URL = '/'
=======
# URL a la que se redirige si el usuario necesita iniciar sesión
LOGIN_URL = '/cuentas/login/' 

# URL a la que se redirige después de un cierre de sesión exitoso
LOGOUT_REDIRECT_URL = '/'

# Fin del archivo settings.py
>>>>>>> 4f114730af45f235e4354b8ed00145427861897c
